version: '3'

services: 
  app:
    build: 
      context: ./node
    container_name: app
    entrypoint: dockerize -wait tcp://db:3306 -timeout 20s docker-entrypoint.sh
    command: bash -c "npm install && node index.js"
    networks: 
        - node-network
    volumes: 
      - ./node:/usr/src/app
    tty: true
    ports: 
      - "3000:3000"

  db: 
    image: mysql:5.7
    command: --innodb-use-native-aio=0 --init-file /data/application/setup.sql
    container_name: db
    restart: always
    tty: true
    volumes: 
      - ./mysql:/var/lib/mysql
      - ./database:/data/application
    environment: 
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=root
    networks: 
      - node-network

  nginx:
    build: 
      context: ./nginx
      dockerfile: Dockerfile.prod
    image: diemerson/nginx:prod
    container_name: nginx
    networks: 
      - node-network
    ports: 
      - "8080:80"

networks: 
  node-network:
    driver: bridge